CREATE TABLE [dbo].[Admin]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[AdminName] NVARCHAR(256) NOT NULL,
	[Username] VARCHAR(50) NOT NULL UNIQUE,
	[Password] CHAR(64) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
	[Salt] CHAR(64) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL DEFAULT '',
	[Status] TINYINT NOT NULL DEFAULT 0
)
