CREATE TABLE [dbo].[Student]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Email] VARCHAR(512) NOT NULL UNIQUE,
	[Password] CHAR(64) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
	[Salt] CHAR(64) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL DEFAULT '',
	[DisplayName] NVARCHAR(256),
	[Status] TINYINT NOT NULL DEFAULT 0,	
)
